/*
 * Copyright (C) 2012-13 MINHAP, Gobierno de España This program is licensed and may be used,
 * modified and redistributed under the terms of the European Public License (EUPL), either version
 * 1.1 or (at your option) any later version as soon as they are approved by the European
 * Commission. Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * more details. You should have received a copy of the EUPL1.1 license along with this program; if
 * not, you may find it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package es.gob.aapp.csvstorage.client.ws.dir3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1 2015-03-23T11:49:59.367+01:00 Generated source
 * version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://impl.manager.directorio.map.es",
    name = "SD01UN_DescargaUnidades")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SD01UNDescargaUnidades {

  @WebResult(name = "exportarReturn", targetNamespace = "http://impl.manager.directorio.map.es",
      partName = "exportarReturn")
  @WebMethod
  public RespuestaWS exportar(
      @WebParam(partName = "unidadesRequest", name = "unidadesRequest") UnidadesWs unidadesRequest);
}
