/*
 * Copyright (C) 2012-13 MINHAP, Gobierno de España This program is licensed and may be used,
 * modified and redistributed under the terms of the European Public License (EUPL), either version
 * 1.1 or (at your option) any later version as soon as they are approved by the European
 * Commission. Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * more details. You should have received a copy of the EUPL1.1 license along with this program; if
 * not, you may find it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package es.gob.aapp.csvstorage.client.ws.dir3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.0.1 2015-03-23T11:49:59.386+01:00 Generated source
 * version: 3.0.1
 * 
 */
@WebServiceClient(name = "SD01UN_DescargaUnidadesService",
    wsdlLocation = "http://dir3ws.redsara.es/directorio/services/SD01UN_DescargaUnidades?wsdl",
    targetNamespace = "http://impl.manager.directorio.map.es")
public class SD01UNDescargaUnidadesService extends Service {

  public final static URL WSDL_LOCATION;

  public final static QName SERVICE =
      new QName("http://impl.manager.directorio.map.es", "SD01UN_DescargaUnidadesService");
  public final static QName SD01UNDescargaUnidades =
      new QName("http://impl.manager.directorio.map.es", "SD01UN_DescargaUnidades");
  static {
    URL url = null;
    try {
      url = new URL("http://dir3ws.redsara.es/directorio/services/SD01UN_DescargaUnidades?wsdl");
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(SD01UNDescargaUnidadesService.class.getName()).log(
          java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
          "http://dir3ws.redsara.es/directorio/services/SD01UN_DescargaUnidades?wsdl");
    }
    WSDL_LOCATION = url;
  }

  public SD01UNDescargaUnidadesService(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public SD01UNDescargaUnidadesService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public SD01UNDescargaUnidadesService() {
    super(WSDL_LOCATION, SERVICE);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public SD01UNDescargaUnidadesService(WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public SD01UNDescargaUnidadesService(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public SD01UNDescargaUnidadesService(URL wsdlLocation, QName serviceName,
      WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   *
   * @return returns SD01UNDescargaUnidades
   */
  @WebEndpoint(name = "SD01UN_DescargaUnidades")
  public SD01UNDescargaUnidades getSD01UNDescargaUnidades() {
    return super.getPort(SD01UNDescargaUnidades, SD01UNDescargaUnidades.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns SD01UNDescargaUnidades
   */
  @WebEndpoint(name = "SD01UN_DescargaUnidades")
  public SD01UNDescargaUnidades getSD01UNDescargaUnidades(WebServiceFeature... features) {
    return super.getPort(SD01UNDescargaUnidades, SD01UNDescargaUnidades.class, features);
  }

}
