/*
 * Copyright (C) 2012-13 MINHAP, Gobierno de España This program is licensed and may be used,
 * modified and redistributed under the terms of the European Public License (EUPL), either version
 * 1.1 or (at your option) any later version as soon as they are approved by the European
 * Commission. Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * more details. You should have received a copy of the EUPL1.1 license along with this program; if
 * not, you may find it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package es.gob.aapp.csvbroker.webservices.querydocument;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1 2017-05-17T16:41:44.668+02:00 Generated source
 * version: 3.0.1
 * 
 */
@WebServiceClient(name = "CSVQueryDocumentCertificateService",
    wsdlLocation = "file:/C:/MINHAP/Workspace_old/csvbroker-client/src/main/wsdl/CSVQueryDocumentCertificateService.wsdl",
    targetNamespace = "urn:es:gob:aapp:csvbroker:webservices:querydocument:v1.0")
public class CSVQueryDocumentCertificateService_Service extends Service {

  public final static URL WSDL_LOCATION;

  public final static QName SERVICE =
      new QName("urn:es:gob:aapp:csvbroker:webservices:querydocument:v1.0",
          "CSVQueryDocumentCertificateService");
  public final static QName CSVQueryDocumentCertificateServicePort =
      new QName("urn:es:gob:aapp:csvbroker:webservices:querydocument:v1.0",
          "CSVQueryDocumentCertificateServicePort");
  static {
    URL url = null;
    try {
      url = new URL(
          "file:/C:/MINHAP/Workspace_old/csvbroker-client/src/main/wsdl/CSVQueryDocumentCertificateService.wsdl");
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(CSVQueryDocumentCertificateService_Service.class.getName())
          .log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
              "file:/C:/MINHAP/Workspace_old/csvbroker-client/src/main/wsdl/CSVQueryDocumentCertificateService.wsdl");
    }
    WSDL_LOCATION = url;
  }

  public CSVQueryDocumentCertificateService_Service(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public CSVQueryDocumentCertificateService_Service(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public CSVQueryDocumentCertificateService_Service() {
    super(WSDL_LOCATION, SERVICE);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public CSVQueryDocumentCertificateService_Service(WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public CSVQueryDocumentCertificateService_Service(URL wsdlLocation,
      WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public CSVQueryDocumentCertificateService_Service(URL wsdlLocation, QName serviceName,
      WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   *
   * @return returns CSVQueryDocumentCertificateService
   */
  @WebEndpoint(name = "CSVQueryDocumentCertificateServicePort")
  public CSVQueryDocumentCertificateService getCSVQueryDocumentCertificateServicePort() {
    return super.getPort(CSVQueryDocumentCertificateServicePort,
        CSVQueryDocumentCertificateService.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns CSVQueryDocumentCertificateService
   */
  @WebEndpoint(name = "CSVQueryDocumentCertificateServicePort")
  public CSVQueryDocumentCertificateService getCSVQueryDocumentCertificateServicePort(
      WebServiceFeature... features) {
    return super.getPort(CSVQueryDocumentCertificateServicePort,
        CSVQueryDocumentCertificateService.class, features);
  }

}
