/*
 * Copyright (C) 2012-13 MINHAP, Gobierno de España This program is licensed and may be used,
 * modified and redistributed under the terms of the European Public License (EUPL), either version
 * 1.1 or (at your option) any later version as soon as they are approved by the European
 * Commission. Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * more details. You should have received a copy of the EUPL1.1 license along with this program; if
 * not, you may find it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package es.gob.aapp.csvstorage.dao.entity.document;

// Generated 28-ago-2012 18:17:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * DocumentNifEntity generated by hbm2java
 */
@Entity
@Table(name = "CSVST_DOCUMENTO_NIF")
public class DocumentNifEntity implements java.io.Serializable {

  /**
   * serialVersionUID
   */
  private static final long serialVersionUID = 1L;
  @Id
  @GeneratedValue(generator = "generator", strategy = GenerationType.SEQUENCE)
  @SequenceGenerator(name = "generator", sequenceName = "CSVST_DOCUMENTO_NIF_SEQ",
      allocationSize = 1)
  private Long id;
  /** Objeto con los datos del organismo. */
  @ManyToOne
  @JoinColumn(name = "ID_DOCUMENTO")
  private DocumentEntity documento;

  @NotEmpty
  /** Cadena con el identificador. */
  @Column(nullable = false, name = "NIF")
  private String nif;

  public DocumentNifEntity(Long id, DocumentEntity documento, String nif) {
    super();
    this.id = id;
    this.documento = documento;
    this.nif = nif;
  }

  public DocumentNifEntity() {
    super();
  }

  /*
   * (non-Javadoc)
   * 
   * @see java.lang.Object#toString()
   */
  @Override
  public String toString() {
    return "DocumentNifEntity [id=" + id + ", documento=" + documento + ", organo=" + nif + "]";
  }

  /**
   * @return the id
   */
  public Long getId() {
    return id;
  }

  /**
   * @param id the id to set
   */
  public void setId(Long id) {
    this.id = id;
  }


  /**
   * @return the nif
   */
  public String getNif() {
    return nif;
  }

  /**
   * @param nif the nif to set
   */
  public void setNif(String nif) {
    this.nif = nif;
  }

  /**
   * @return the documentoEni
   */
  public DocumentEntity getDocumento() {
    return documento;
  }

  /**
   * @param documento the documento to set
   */
  public void setDocumento(DocumentEntity documento) {
    this.documento = documento;
  }

}
