/*
 * Copyright (C) 2012-13 MINHAP, Gobierno de España This program is licensed and may be used,
 * modified and redistributed under the terms of the European Public License (EUPL), either version
 * 1.1 or (at your option) any later version as soon as they are approved by the European
 * Commission. Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * more details. You should have received a copy of the EUPL1.1 license along with this program; if
 * not, you may find it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package es.gob.aapp.csvstorage.dao.entity.document;


import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * DocumentRestriccionEntity generated by hbm2java
 */
@Entity
@Table(name = "CSVST_DOCUMENTO_TIPO_ID")
public class DocumentIdsEntity implements java.io.Serializable {

  /**
   * serialVersionUID
   */
  private static final long serialVersionUID = 1L;
  @Id
  @GeneratedValue(generator = "generator", strategy = GenerationType.SEQUENCE)
  @SequenceGenerator(name = "generator", sequenceName = "CSVST_DOCUMENTO_TIPOID_SEQ",
      allocationSize = 1)
  private Long id;

  /** Objeto con los datos del organismo. */
  @ManyToOne
  @JoinColumn(name = "ID_DOCUMENTO")
  private DocumentEntity documento;

  @NotNull
  @Column(name = "ID_TIPO_IDENTIFICACION")
  private Integer tipoId;

  public DocumentIdsEntity(Long id, DocumentEntity documento, Integer tipoId) {
    super();
    this.id = id;
    this.documento = documento;
    this.tipoId = tipoId;
  }

  public DocumentIdsEntity() {
    super();
  }

  /*
   * (non-Javadoc)
   * 
   * @see java.lang.Object#toString()
   */
  @Override
  public String toString() {
    return "DocumentRestriccionEntity [id=" + id + ", documento=" + documento + ", tipoId=" + tipoId
        + "]";
  }

  /**
   * @return the id
   */
  public Long getId() {
    return id;
  }

  /**
   * @param id the id to set
   */
  public void setId(Long id) {
    this.id = id;
  }


  /**
   * @return the restriccion
   */
  public Integer getTipoId() {
    return tipoId;
  }

  /**
   * @param tipoId the restriccion to set
   */
  public void setTipoId(Integer tipoId) {
    this.tipoId = tipoId;
  }

  /**
   * @return the documentoEni
   */
  public DocumentEntity getDocumento() {
    return documento;
  }

  /**
   * @param documento the documento to set
   */
  public void setDocumento(DocumentEntity documento) {
    this.documento = documento;
  }

}
